language: node_js
node_js:
  - "node"
  - "iojs"

notifications:
  slack: polyglotted:oI752wOHgUY3xWHyCqXRhLs3

before_install:
  - npm i -g codeclimate-test-reporter
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_script:
  - CODECLIMATE_REPO_TOKEN=982c84dade1cda77911fd7eba4a84bbba81cb347b8337f9521ff0b2cbd2779cb codeclimate < report/jasmine-coverage/lcov.info
