sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
env:
  - NO_WATCH_TESTS=1

before_install:
  - '[ "${TRAVIS_NODE_VERSION}" != "0.10" ] || npm install -g npm'
  - 'npm i -g babel'

after_success: cat ./coverage/lcov.info | node_modules/.bin/coveralls --verbose && rm -rf ./coverage